### PR TITLE
fix equation 3

### PR DESCRIPTION
**Pull request by chohner**
a1/a0 and a2/a0 were mis-formatted

### CODE REVIEW

**Comment by rtoy** [comment]
This is fixed in https://github.com/WebAudio/Audio-EQ-Cookbook.  (Many thanks to @shepazu for doing the initial hard work on this!)

**Comment by shepazu** [comment]
I just want to be clear that this is not _my_ hard work. I only converted Robert Bristow-Johnson's [original text document](https://www.musicdsp.org/en/latest/Filters/197-rbj-audio-eq-cookbook.html) into HTML+MathML, with his permission. All credit goes to RBJ, not to me.

**Comment by rtoy** [comment]
@chohner Can you check the latest version? I think these are all fixed now.

**Comment by chohner** [comment]
all good now!

**Pull request closed without merging**
